import 'package:riskflow_fx/features/risk/models/instrument.dart';

const supportedInstruments = <Instrument>[
  Instrument(
    symbol: 'EURUSD',
    label: 'EUR/USD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.09,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'GBPUSD',
    label: 'GBP/USD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.28,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'AUDUSD',
    label: 'AUD/USD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 0.66,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'NZDUSD',
    label: 'NZD/USD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 0.61,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'USDCAD',
    label: 'USD/CAD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.35,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'USDCHF',
    label: 'USD/CHF',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 0.88,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'USDJPY',
    label: 'USD/JPY',
    category: 'forex',
    pipSize: 0.01,
    pipValuePerStandardLot: 9.1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 150.25,
    pricePrecision: 3,
  ),
  Instrument(
    symbol: 'EURJPY',
    label: 'EUR/JPY',
    category: 'forex',
    pipSize: 0.01,
    pipValuePerStandardLot: 9.1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 163.40,
    pricePrecision: 3,
  ),
  Instrument(
    symbol: 'AUDJPY',
    label: 'AUD/JPY',
    category: 'forex',
    pipSize: 0.01,
    pipValuePerStandardLot: 9.1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 98.20,
    pricePrecision: 3,
  ),
  Instrument(
    symbol: 'GBPJPY',
    label: 'GBP/JPY',
    category: 'forex',
    pipSize: 0.01,
    pipValuePerStandardLot: 9.1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 191.8,
    pricePrecision: 3,
  ),
  Instrument(
    symbol: 'EURGBP',
    label: 'EUR/GBP',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 0.85,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'EURAUD',
    label: 'EUR/AUD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.65,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'GBPAUD',
    label: 'GBP/AUD',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.95,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'GBPCHF',
    label: 'GBP/CHF',
    category: 'forex',
    pipSize: 0.0001,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 1.12,
    pricePrecision: 5,
  ),
  Instrument(
    symbol: 'XAUUSD',
    label: 'XAU/USD (Gold)',
    category: 'metal',
    pipSize: 0.1,
    pipValuePerStandardLot: 10,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 2185.0,
    pricePrecision: 2,
  ),
  Instrument(
    symbol: 'XAGUSD',
    label: 'XAG/USD (Silver)',
    category: 'metal',
    pipSize: 0.01,
    pipValuePerStandardLot: 50,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 24.80,
    pricePrecision: 3,
  ),
  Instrument(
    symbol: 'US30',
    label: 'US30 (Dow)',
    category: 'index',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 39500,
    pricePrecision: 1,
  ),
  Instrument(
    symbol: 'US100',
    label: 'US100 (Nasdaq)',
    category: 'index',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 18200,
    pricePrecision: 1,
  ),
  Instrument(
    symbol: 'US500',
    label: 'US500 (S&P 500)',
    category: 'index',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 5200,
    pricePrecision: 1,
  ),
  Instrument(
    symbol: 'GER40',
    label: 'GER40 (DAX)',
    category: 'index',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 18700,
    pricePrecision: 1,
  ),
  Instrument(
    symbol: 'UK100',
    label: 'UK100 (FTSE)',
    category: 'index',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 8200,
    pricePrecision: 1,
  ),
  Instrument(
    symbol: 'BTCUSD',
    label: 'BTC/USD',
    category: 'crypto',
    pipSize: 1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 68000,
    pricePrecision: 2,
  ),
  Instrument(
    symbol: 'ETHUSD',
    label: 'ETH/USD',
    category: 'crypto',
    pipSize: 0.1,
    pipValuePerStandardLot: 1,
    minLot: 0.01,
    lotStep: 0.01,
    fallbackPrice: 3500,
    pricePrecision: 2,
  ),
];
